name: Frontend ReactJS

on:
  push:
    branches:
      - 'feature/[0-9]+-*'
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 16.x
  ARTIFACT_APP: application-artifact
  ARTIFACT_COVERAGE: coverage-artifact

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci

      - name: Coverage
        run: npm run coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_COVERAGE }}
          path: coverage

  Build:
    needs: Test
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci

      - name: Build app
        run: npm run build

      - name: Upload application artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_APP }}
          path: build

  Deploy:
    if: github.ref.name == 'main'
    needs: [Test, Build]
    runs-on: ubuntu-latest

    steps:
      - name: Download application artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.ARTIFACT_APP }}

      #- name: Docker login

      #- name: Docker build
